package com.example.diagnostictool

import android.Manifest
import android.content.Intent
import android.content.pm.PackageManager
import android.net.Uri
import android.os.Build
import android.os.Bundle
import android.provider.MediaStore
import android.view.Gravity
import android.view.WindowManager
import android.widget.Button
import android.widget.EditText
import android.widget.LinearLayout
import android.widget.ScrollView
import android.widget.TextView
import android.widget.Toast
import androidx.appcompat.app.AlertDialog
import androidx.appcompat.app.AppCompatActivity
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

class NewMainActivity : AppCompatActivity() {
    private lateinit var status:TextView;private lateinit var obdValues:TextView;private lateinit var recordButton:Button;private lateinit var recordStatus:TextView;private lateinit var currentCarText:TextView;private lateinit var connectButton:Button;private lateinit var obd:TargetElm327Ble
    private var recorder:PublicSessionRecorder?=null;private val carStore by lazy{CarStore(this)};private val recordStore by lazy{DiagnosticRecordStore(this)};private val requestCode=10;private var pendingConnect=false;private var lastSessionUris:List<Uri>=emptyList();private var pendingConclusionSession:String?=null
    override fun onCreate(savedInstanceState:Bundle?){super.onCreate(savedInstanceState);window.addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);setContentView(R.layout.activity_main);val root=findViewById<ScrollView>(R.id.mainRoot);val id=resources.getIdentifier("status_bar_height","dimen","android");val top=if(id>0)resources.getDimensionPixelSize(id) else 0;root.setPadding(root.paddingLeft,top,root.paddingRight,root.paddingBottom);status=findViewById(R.id.status);obdValues=findViewById(R.id.obdValues);recordButton=findViewById(R.id.record);recordStatus=findViewById(R.id.recordStatus);currentCarText=findViewById(R.id.currentCar);connectButton=findViewById(R.id.connect);findViewById<Button>(R.id.changeCar).setOnClickListener{showCarsDialog()};findViewById<Button>(R.id.addCar).setOnClickListener{showCarEditor(carStore.create(),true)};findViewById<Button>(R.id.history).setOnClickListener{showHistory()};connectButton.setOnClickListener{requestAndConnect()};recordButton.setOnClickListener{toggleRecording()};configureObd();enterCarFlow()}
    private fun enterCarFlow(){val cars=carStore.all();when(cars.size){0->showFirstCarDialog();1->{carStore.select(cars[0].id);refreshCarUi()};else->showCarsDialog()}}
    private fun showFirstCarDialog(){AlertDialog.Builder(this).setTitle("Добавьте автомобиль").setMessage("Чтобы начать сбор информации, сначала добавьте автомобиль.").setPositiveButton("Добавить автомобиль"){_,_->showCarEditor(carStore.create(),true)}.setCancelable(false).show()}
    fun hasLocationPermission():Boolean=if(Build.VERSION.SDK_INT<23)true else checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)==PackageManager.PERMISSION_GRANTED||checkSelfPermission(Manifest.permission.ACCESS_COARSE_LOCATION)==PackageManager.PERMISSION_GRANTED
    private fun refreshCarUi(){val car=carStore.selected();if(car==null){currentCarText.text="Автомобиль не выбран";connectButton.isEnabled=false;recordButton.isEnabled=false;return};currentCarText.text=car.title();connectButton.isEnabled=true;recordButton.isEnabled=true}
    private fun configureObd(){if(::obd.isInitialized)obd.close();obd=TargetElm327Ble(this,object:TargetElm327Ble.Listener{override fun onState(text:String){runOnUiThread{status.text=text};if(text.contains("ELM327")&&text.contains("готов"))recorder?.setObdActive(true);if(text.contains("отключён",true))recorder?.setObdActive(false)};override fun onData(values:ObdValues,monotonicNs:Long){runOnUiThread{obdValues.text=values.toDisplay()};recorder?.onObd(values,monotonicNs)};override fun onDevices(devices:List<TargetElm327Ble.DeviceInfo>)=runOnUiThread{showObdDevices(devices)}});status.text="OBD-адаптер не подключён — запись возможна с GPS"}
    private fun showObdDevices(devices:List<TargetElm327Ble.DeviceInfo>){if(devices.isEmpty()){AlertDialog.Builder(this).setTitle("OBD-адаптеры не найдены").setMessage("Проверьте питание ELM327 и Bluetooth.").setPositiveButton("ОК",null).show();return};val labels=devices.map{it.label()}.toTypedArray();AlertDialog.Builder(this).setTitle("Выберите OBD-адаптер").setSingleChoiceItems(labels,-1){dialog,which->val d=devices[which];dialog.dismiss();status.text="Подключение: ${d.label().replace("\n"," — ")}";obd.connect(d.device)}.setNegativeButton("Отмена",null).show()}
    private fun showCarsDialog(){val cars=carStore.all();if(cars.isEmpty()){showFirstCarDialog();return};val labels=cars.map{it.title()}.toTypedArray();val selected=cars.indexOfFirst{it.id==carStore.selectedId()}.coerceAtLeast(0);AlertDialog.Builder(this).setTitle("Выберите автомобиль").setSingleChoiceItems(labels,selected){dialog,which->carStore.select(cars[which].id);refreshCarUi();dialog.dismiss()}.setNeutralButton("Изменить"){_,_->showCarEditor(cars[selected],false)}.setPositiveButton("Добавить"){_,_->showCarEditor(carStore.create(),true)}.setNegativeButton("Закрыть",null).show()}
    private fun showCarEditor(car:Car,returnToDiagnostic:Boolean){val scroll=ScrollView(this);val form=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(40,8,40,0)};scroll.addView(form);fun field(hint:String,value:String="")=EditText(this).apply{this.hint=hint;setText(value);setSingleLine(true);setOnFocusChangeListener{_,hasFocus->if(hasFocus)scroll.post{scroll.smoothScrollTo(0,top)}};form.addView(this)};val make=field("Марка *",car.make);val model=field("Модель *",car.model);val year=field("Год выпуска *",car.year);val engine=field("Двигатель / объём *",car.engine);val fuel=field("Топливо *",car.fuel);val transmission=field("Коробка передач *",car.transmission);val drive=field("Привод *",car.drive);val mileage=field("Пробег, км *",car.mileage);val vin=field("VIN (необязательно)",car.vin);val notes=field("Дополнительная информация (необязательно)",car.notes);val dialog=AlertDialog.Builder(this).setTitle(if(car.make.isBlank()&&car.model.isBlank())"Добавить автомобиль" else "Автомобиль").setView(scroll).setNegativeButton("Отмена"){_,_->if(returnToDiagnostic&&carStore.all().isEmpty())showFirstCarDialog()}.setPositiveButton("Сохранить",null).create();dialog.setOnShowListener{dialog.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener{val missing=mutableListOf<String>();if(make.text.isNullOrBlank()){make.error="Обязательное поле";missing+="Марка"};if(model.text.isNullOrBlank()){model.error="Обязательное поле";missing+="Модель"};if(year.text.isNullOrBlank()){year.error="Обязательное поле";missing+="Год выпуска"};if(engine.text.isNullOrBlank()){engine.error="Обязательное поле";missing+="Двигатель / объём"};if(fuel.text.isNullOrBlank()){fuel.error="Обязательное поле";missing+="Топливо"};if(transmission.text.isNullOrBlank()){transmission.error="Обязательное поле";missing+="Коробка передач"};if(drive.text.isNullOrBlank()){drive.error="Обязательное поле";missing+="Привод"};if(mileage.text.isNullOrBlank()){mileage.error="Обязательное поле";missing+="Пробег"};if(missing.isNotEmpty()){Toast.makeText(this,"Заполните: ${missing.joinToString(", ")}",Toast.LENGTH_LONG).show();return@setOnClickListener};car.make=make.text.toString().trim();car.model=model.text.toString().trim();car.year=year.text.toString().trim();car.engine=engine.text.toString().trim();car.fuel=fuel.text.toString().trim();car.transmission=transmission.text.toString().trim();car.drive=drive.text.toString().trim();car.mileage=mileage.text.toString().trim();car.vin=vin.text.toString().trim();car.notes=notes.text.toString().trim();carStore.save(car);carStore.select(car.id);refreshCarUi();dialog.dismiss()}};dialog.show();dialog.window?.setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE)}
    private fun showHistory(){val car=carStore.selected()?:run{showFirstCarDialog();return};val records=recordStore.forCar(car.id);val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(28,8,28,8)};if(records.isEmpty())box.addView(TextView(this).apply{text="Диагностик пока нет.";textSize=16f}) else records.forEach{r->val date=SimpleDateFormat("dd.MM.yyyy HH:mm",Locale.getDefault()).format(Date(r.createdAt));box.addView(TextView(this).apply{text="$date\nСеанс: ${r.sessionName}\n${r.complaint.ifBlank{"Жалоба не указана"}}";textSize=16f});box.addView(TextView(this).apply{text=when{r.aiResponseUri!=null->"ИИ: ответ получен";r.aiSent->"ИИ: отправлено, ответа пока нет";else->"ИИ: не отправлено"};textSize=14f});val row=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL};if(!r.aiSent)row.addView(Button(this).apply{text="Отправить ИИ";setOnClickListener{shareHistoricalSession(car,r)}});if(r.aiSent&&r.aiResponseUri==null)row.addView(Button(this).apply{text="Добавить заключение";setOnClickListener{pickConclusion(r.sessionName)}});if(r.aiResponseUri!=null)row.addView(Button(this).apply{text="Скачать заключение";setOnClickListener{saveConclusionToDownloads(Uri.parse(r.aiResponseUri),r.sessionName)}});box.addView(row);box.addView(TextView(this).apply{setPadding(0,0,0,12)})};AlertDialog.Builder(this).setTitle("История диагностики — ${car.title()}").setView(ScrollView(this).apply{addView(box)}).setPositiveButton("Закрыть",null).show()}
    private fun findSessionUris(sessionName:String):List<Uri>{if(Build.VERSION.SDK_INT<29)return emptyList();val result=mutableListOf<Uri>();for(name in listOf("audio.wav","obd.csv","gps.csv","sensors.csv","session.json")){contentResolver.query(MediaStore.Downloads.EXTERNAL_CONTENT_URI,arrayOf(MediaStore.Downloads._ID),"${MediaStore.Downloads.DISPLAY_NAME}=? AND ${MediaStore.Downloads.RELATIVE_PATH}=?",arrayOf(name,"Download/DiagnosticTool/sessions/$sessionName"),null)?.use{if(it.moveToFirst())result+=Uri.withAppendedPath(MediaStore.Downloads.EXTERNAL_CONTENT_URI,it.getLong(0).toString())}};return result}
    private fun shareHistoricalSession(car:Car,r:DiagnosticRecordStore.Record){val uris=findSessionUris(r.sessionName);if(uris.isEmpty()){AlertDialog.Builder(this).setTitle("Файлы сессии не найдены").setMessage("Не удалось найти сохранённые данные этой сессии.").setPositiveButton("ОК",null).show();return};val text="Проанализируй диагностическую сессию автомобиля. Автомобиль: ${car.title()}. Параметры: ${car.subtitle()}. Жалоба: ${r.complaint.ifBlank{"не указана"}}. Сопоставь audio.wav, obd.csv, gps.csv, sensors.csv и session.json по общей временной шкале и дай техническое заключение.";recordStore.markAiSent(r.sessionName);val i=Intent(Intent.ACTION_SEND_MULTIPLE).apply{type="application/octet-stream";putExtra(Intent.EXTRA_TEXT,text);putParcelableArrayListExtra(Intent.EXTRA_STREAM,ArrayList(uris));addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)};startActivity(Intent.createChooser(i,"Передать диагностическую сессию в ИИ"))}
    private fun pickConclusion(sessionName:String){pendingConclusionSession=sessionName;startActivityForResult(Intent(Intent.ACTION_OPEN_DOCUMENT).apply{type="application/pdf";addCategory(Intent.CATEGORY_OPENABLE);addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION or Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION)},200)}
    override fun onActivityResult(requestCode:Int,resultCode:Int,data:Intent?){super.onActivityResult(requestCode,resultCode,data);if(requestCode==200&&resultCode==RESULT_OK&&data?.data!=null){val uri=data.data!!;try{contentResolver.takePersistableUriPermission(uri,data.flags and (Intent.FLAG_GRANT_READ_URI_PERMISSION or Intent.FLAG_GRANT_WRITE_URI_PERMISSION))}catch(_:Exception){};pendingConclusionSession?.let{recordStore.setAiResponse(it,uri.toString())};pendingConclusionSession=null;showHistory()}}
    private fun saveConclusionToDownloads(uri:Uri,sessionName:String){try{val values=android.content.ContentValues().apply{put(MediaStore.Downloads.DISPLAY_NAME,"Заключение_$sessionName.pdf");put(MediaStore.Downloads.MIME_TYPE,"application/pdf");put(MediaStore.Downloads.RELATIVE_PATH,"Download/DiagnosticTool/conclusions");put(MediaStore.Downloads.IS_PENDING,1)};val outUri=contentResolver.insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI,values)?:throw IllegalStateException("Не удалось создать файл");contentResolver.openInputStream(uri)?.use{input->contentResolver.openOutputStream(outUri)?.use{output->input.copyTo(output)}}?:throw IllegalStateException("Не удалось прочитать заключение");contentResolver.update(outUri,ContentValues().apply{put(MediaStore.Downloads.IS_PENDING,0)},null,null);Toast.makeText(this,"Заключение сохранено в Downloads/DiagnosticTool/conclusions",Toast.LENGTH_LONG).show()}catch(e:Exception){Toast.makeText(this,"Ошибка сохранения: ${e.message}",Toast.LENGTH_LONG).show()}}
    private fun openUri(uri:Uri){try{startActivity(Intent(Intent.ACTION_VIEW).apply{setDataAndType(uri,"application/pdf");addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)})}catch(_:Exception){startActivity(Intent(Intent.ACTION_VIEW).setData(uri))}}
    private fun requestAndConnect(){val permissions=mutableListOf<String>();if(Build.VERSION.SDK_INT>=31){permissions+=Manifest.permission.BLUETOOTH_SCAN;permissions+=Manifest.permission.BLUETOOTH_CONNECT};pendingConnect=true;if(permissions.any{checkSelfPermission(it)!=PackageManager.PERMISSION_GRANTED})requestPermissions(permissions.toTypedArray(),requestCode)else{configureObd();obd.scan()}}
    override fun onRequestPermissionsResult(request:Int,permissions:Array<out String>,results:IntArray){super.onRequestPermissionsResult(request,permissions,results);if(request==requestCode&&pendingConnect&&results.all{it==PackageManager.PERMISSION_GRANTED}){configureObd();obd.scan()};pendingConnect=false}
    private fun toggleRecording(){val car=carStore.selected()?:run{showFirstCarDialog();return};if(recorder==null){val needed=if(Build.VERSION.SDK_INT>=23)arrayOf(Manifest.permission.RECORD_AUDIO,Manifest.permission.ACCESS_FINE_LOCATION)else arrayOf(Manifest.permission.RECORD_AUDIO);if(needed.any{checkSelfPermission(it)!=PackageManager.PERMISSION_GRANTED}){pendingConnect=false;requestPermissions(needed,requestCode);return};val r=PublicSessionRecorder(this,car){text->runOnUiThread{recordStatus.text=text}};recorder=r;r.start();recordButton.text="ОСТАНОВИТЬ ЗАПИСЬ"}else{val r=recorder?:return;r.stop();lastSessionUris=r.sessionUris();recorder=null;recordButton.text="НАЧАТЬ ЗАПИСЬ";showPostRecordDialog(car,r.sessionName)}}
    private fun showPostRecordDialog(car:Car,sessionName:String){val input=EditText(this).apply{hint="Что вас беспокоит? (необязательно)";minLines=4;gravity=Gravity.TOP};AlertDialog.Builder(this).setTitle("Диагностическая сессия завершена").setMessage("${car.title()}\nСессия: $sessionName").setView(input).setNegativeButton("Закрыть"){_,_->recordStore.add(car.id,sessionName,input.text.toString().trim())}.setPositiveButton("АНАЛИЗИРОВАТЬ ИИ"){_,_->recordStore.add(car.id,sessionName,input.text.toString().trim());shareSessionWithAi(car,sessionName,input.text.toString().trim())}.show()}
    private fun shareSessionWithAi(car:Car,sessionName:String,complaint:String){if(lastSessionUris.isEmpty()){AlertDialog.Builder(this).setTitle("Данные недоступны").setMessage("Не удалось получить файлы диагностической сессии.").setPositiveButton("ОК",null).show();return};val prompt="Проанализируй диагностическую сессию автомобиля. Автомобиль: ${car.title()}. Параметры: ${car.subtitle()}. Сессия: $sessionName. Жалоба: ${complaint.ifBlank{"не указана"}}. Во вложениях audio.wav, obd.csv, gps.csv, sensors.csv, session.json. Сопоставь их по общей временной шкале, найди условия возникновения неисправности, отличай корреляцию от доказательства причины и дай техническое заключение с конкретными проверками.";recordStore.markAiSent(sessionName);val intent=Intent(Intent.ACTION_SEND_MULTIPLE).apply{type="application/octet-stream";putExtra(Intent.EXTRA_TEXT,prompt);putParcelableArrayListExtra(Intent.EXTRA_STREAM,ArrayList(lastSessionUris));addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)};startActivity(Intent.createChooser(intent,"Передать диагностическую сессию в ИИ"))}
    override fun onDestroy(){recorder?.stop();recorder=null;if(::obd.isInitialized)obd.close();super.onDestroy()}
}
